import Head from 'next/head';

import Main from './components/Main/page';
import SchemaSection from './components/SchemaSection/page';
import TrainingSection from './components/TrainingSection/page';
import ReviewsSection from './components/ReviewsSection/page';
import InstagramSection from './components/InstagramSection/page';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <Main />
        <SchemaSection />
        <TrainingSection />
        <ReviewsSection />
        <InstagramSection />
      </div>
    </>
  );
}
